/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifsp.scfa.view;

import javax.swing.JDialog;

/**
 *
 * @author macel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuBebida = new javax.swing.JMenuItem();
        jMenuAlimento = new javax.swing.JMenuItem();
        jMenuUsuário = new javax.swing.JMenuItem();
        jMenuMaterial = new javax.swing.JMenuItem();
        jMenuOrcamento = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        sbmMovimentacaoPorPeriodo = new javax.swing.JMenuItem();
        sbmSistema = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas - Tela Principal");
        setExtendedState(6);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fundo.jpg"))); // NOI18N

        menuCadastro.setText("Cadastro");
        menuCadastro.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        jMenuCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuCliente.setText("Cliênte");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuCliente);

        jMenuBebida.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuBebida.setText("Bebida");
        jMenuBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBebidaActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuBebida);

        jMenuAlimento.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuAlimento.setText("Alimento");
        jMenuAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlimentoActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuAlimento);

        jMenuUsuário.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuUsuário.setText("Usuário");
        jMenuUsuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuárioActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuUsuário);

        jMenuMaterial.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuMaterial.setText("Material");
        jMenuMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMaterialActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuMaterial);

        jMenuBar1.add(menuCadastro);

        jMenuOrcamento.setText("Orçamento");
        jMenuOrcamento.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenuItem4.setText("Orçamento");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuOrcamento.add(jMenuItem4);

        jMenuBar1.add(jMenuOrcamento);

        menuRelatorios.setText("Relatorios");
        menuRelatorios.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N

        sbmMovimentacaoPorPeriodo.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        sbmMovimentacaoPorPeriodo.setText("Orçamento");
        menuRelatorios.add(sbmMovimentacaoPorPeriodo);

        sbmSistema.setText("Clientes");
        sbmSistema.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        menuRelatorios.add(sbmSistema);

        jMenuBar1.add(menuRelatorios);

        jMenu4.setText("Sair");
        jMenu4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(915, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sbmServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmServidorActionPerformed
//     //new DialogDadosServidor().setVisible(true);
//        FormServidor form = new FormServidor(this, true);
//        form.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
//        form.setTitle("Manutenção do Servidor");
//        form.setLocationRelativeTo(null);
//        form.setResizable(false);
//        form.setVisible(true);
    }//GEN-LAST:event_sbmServidorActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        // VisaoOrcamentoOLD  c= new VisaoOrcamentoOLD(this, true);
        //c.setVisible(true);
        PesquisaCliente tela = new PesquisaCliente(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void jMenuUsuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuárioActionPerformed
        // TODO add your handling code here:
        VisaoUsuario  c= new VisaoUsuario(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuUsuárioActionPerformed

    private void jMenuAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlimentoActionPerformed
        // TODO add your handling code here:
        VisaoAlimento  c= new VisaoAlimento(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuAlimentoActionPerformed

    private void jMenuBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBebidaActionPerformed
        // TODO add your handling code here:
        VisaoBebida  c= new VisaoBebida(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuBebidaActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        // TODO add your handling code here:
        VisaoCliente  c= new VisaoCliente(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMaterialActionPerformed
        // TODO add your handling code here:
        VisaoUtensilio  c = new VisaoUtensilio(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuAlimento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBebida;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuMaterial;
    private javax.swing.JMenu jMenuOrcamento;
    private javax.swing.JMenuItem jMenuUsuário;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem sbmMovimentacaoPorPeriodo;
    private javax.swing.JMenu sbmSistema;
    // End of variables declaration//GEN-END:variables
}
