/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ifsp.scfa.view;

import edu.ifsp.scfa.control.UsuarioDAO;
import edu.ifsp.scfa.model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Programar
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();

    }

    private UsuarioDAO controle = new UsuarioDAO();

    public boolean existCamposVazio() {
        if (txtInicioLogin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo LOGIN deve ser Prenchido", "Atenção", JOptionPane.ERROR_MESSAGE);
            txtInicioLogin.requestFocus();
            return true;
        }

        if (String.valueOf(txtSenha.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo SENHA deve ser Prenchido", "Atenção", JOptionPane.ERROR_MESSAGE);
            txtSenha.requestFocus();
            return true;
        }
        return false;

    }

    /**
     * *
     * ESTE METODO VERIFICA SE O USUARIO TEM LOGIN E SENHA CADASTRADOS
     */
    public void verificaUsuario() {
        Usuario usuario = null;
        String login = txtInicioLogin.getText();
        String senha = String.valueOf(txtSenha.getPassword());
        usuario = controle.confirmaUsuario(login, senha);

        // verificando o usuario
        if (usuario != null) {
            // System.out.println("login: " + usuario.getLogin() + "senha: " + usuario.getSenha());//so para teste

            TelaPrincipal tela = new TelaPrincipal();
            this.dispose();
            tela.setVisible(true);
            

        } else if (login.equals("scfa") && senha.equals("scfa")) {
            TelaPrincipal tela = new TelaPrincipal();
            this.dispose();
            tela.setVisible(true);
           

        } else {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado!!! verifique login e senha!", "Atenção", JOptionPane.ERROR_MESSAGE);
            txtInicioLogin.setText("");
            txtSenha.setText("");
            txtInicioLogin.requestFocus();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        jButtonAcessar = new javax.swing.JButton();
        jLabelSenha = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        txtInicioLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonSair.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(140, 120, 70, 30);

        jButtonAcessar.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jButtonAcessar.setText("Acessar");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(30, 120, 90, 30);

        jLabelSenha.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(20, 70, 70, 19);

        jLabelUsuario.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(20, 40, 60, 19);
        getContentPane().add(txtInicioLogin);
        txtInicioLogin.setBounds(90, 30, 130, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(90, 70, 130, 30);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/tl.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 241, 183);

        setSize(new java.awt.Dimension(257, 221));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed

        if (!existCamposVazio()) {
            verificaUsuario();

        }


    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField txtInicioLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
